name: RankGift
main: me.herex.rankgift.RankGiftPlugin
version: 1.0.0
author: HereX
api-version: 1.13
commands:
  gift:
    usage: /gift <player>
  giftaccept:
    usage: /giftaccept
  giftdeny:
    usage: /giftdeny
  rankgift:
    usage: /rankgift reload
permissions:
  rankgift.admin:
    default: op
